### ISSUE TITLE
[Jar] Practice

### ISSUE THREAD

**Issue by MLGMAG** [Buga1chukY/JavaPractice#20]
Do this tasks without IntelliJ.

1. Take simple program. (print `hello world`)
1.1. Compile this program.
1.2. Run it with hands.

2. What is the `String args[]` parameter in the main method?

3. Take a program, that request args. (for example, sum program. It takes 2 arguments and return sum)
3.1. Compile this program.
3.2. Run it with hands.

4. What is Jar / War / Ear?

5. Make the same thing as in item 1, but based on the jar. 

6. Make the same thing as in item 2, but based on the jar.

**Comment by Buga1chukY** [comment]
![image](https://github.com/Buga1chukY/JavaPractice/assets/123409653/c32a6386-c63f-4693-be63-cac05aa013c3)
1. Done
1.1. Done
1.2. Done

**Comment by Buga1chukY** [comment]
2. The String[] args parameter in the main method is an array of strings that allows the program to accept command-line arguments.

**Comment by Buga1chukY** [comment]
3. Done
3.1. Done
3.2. Done
![image](https://github.com/Buga1chukY/JavaPractice/assets/123409653/0896b1a2-0d89-47d4-bca9-119a4c44d7e6)

**Comment by Buga1chukY** [comment]
4. JAR (Java Archive), WAR (Web Archive), and EAR (Enterprise Archive) are file formats used to package and distribute Java applications.

**Comment by Buga1chukY** [comment]
5. Done
![image](https://github.com/Buga1chukY/JavaPractice/assets/123409653/6a4eeb53-5147-4c7c-a138-20214fbf63a9)

**Comment by Buga1chukY** [comment]
6. Done
![image](https://github.com/Buga1chukY/JavaPractice/assets/123409653/48eae93a-3cae-4954-beef-3499e664cdb7)

**Comment by MLGMAG** [comment]
Add an article to the [notes repo](https://github.com/Buga1chukY/Notes).
With all CLI commands / screenshots.

**Comment by Buga1chukY** [comment]
Done in [https://github.com/Buga1chukY/Notes/commit/0e85f455f9158b6a9fd57bb726f125e4009338ee](url)

**Comment by Buga1chukY** [comment]
Done in [https://github.com/Buga1chukY/Notes/commit/9383c01b92608e1a2923fd3d90b82f8128b5cb4b](url)
